### ISSUE TITLE
Bug: Pen tool issues

### ISSUE THREAD

**Issue by KyoGrou** [photopea/photopea#1441]
- It's really hard to close a Path since I have to click exactly right on the start point. Can you make it snap when the pointer is near the start point of the path ?
- When I closed a path and want to create a new path, using the Unite mode, the pen will create new points for the previous closed path, instead of create a new one.
- When using the pen and the path select tools, the Delete key can't delete the layers

**Comment by KyoGrou** [comment]
- When using pen tool with Shift + Left click, it will create a point with handles instead of points only.
- Closing the path made the handle of the start point pointed at different direction.
![image](https://user-images.githubusercontent.com/30156458/59022211-84158780-8877-11e9-934a-94fa8cc4aaaa.png) 
![image](https://user-images.githubusercontent.com/30156458/59022225-8c6dc280-8877-11e9-92ed-33d17c4398b3.png)

- When the pen tool is at Shape mode, Shift click won't create anything, then if you release the Shift key and click, there will be shape layers with the exactly number of time you Shift click.
![image](https://user-images.githubusercontent.com/30156458/59022467-056d1a00-8878-11e9-860b-09e55d418114.png)

- When the pen tool is at Path mode, Shift click make Photopea frozen.

**Comment by photopea** [comment]
- It's really hard to close a Path since I have to click exactly right on the start point. Can you make it snap when the pointer is near the start point of the path ?
---- The path should be closed when you are near the path, there is a tolerance of 4 pixels
- When I closed a path and want to create a new path, using the Unite mode, the pen will create new points for the previous closed path, instead of create a new one.
---- When any knot is selected, the new knot will be added to the same path after the selected knot. Just deselect the knot with the Escape key.
- When using the pen and the path select tools, the Delete key can't delete the layers
---- In this case, the Delete key deletes paths / knots, and can not be used to delete layers.

**Comment by photopea** [comment]
- When using pen tool with Shift + Left click, it will create a point with handles instead of points only.
---- Did you drag the point after pressing the mouse? I think this works the same as Adobe Photosohp and other editors. 
- Closing the path made the handle of the start point pointed at different direction.
---- When closing, the final position will determine the direction of both handles.

I fixed the error when starting a new path with a Shift key down.

**Comment by KyoGrou** [comment]
- In this case, the Delete key deletes paths / knots, and can not be used to delete layers.
---- When you press the delete key in Photoshop, if there's no path selected, the layer will be deleted. And if you choose the other raster / group layers, the delete key will do it's job.
- When using pen tool with Shift + Left click, it will create a point with handles instead of points only.
---- This turn out to be a problem when using pen tablet. I have no issue with the mouse. When I shift + click, the handle's length is about the same length from where the point is created connect to where I clicked. I'm using wacom tablet.
![image](https://user-images.githubusercontent.com/30156458/59028948-2b4deb00-8887-11e9-928f-0e014e6dd6ef.png)
- When closing, the final position will determine the direction of both handles.
---- This behavior is confusing, since when you start creating a point, you have already determined the handle's direction according to the path's shape you want, and when you close it, you have to edit it again, which is why I considered it as a bug.

**Comment by photopea** [comment]
When you close path and just click (without moving with a mouse down), the original direction of handles is not changed.

**Comment by KyoGrou** [comment]
I'm still having the close path problem at my side, both the close path distance and the direction of handles problems.

**Comment by photopea** [comment]
How exactly does it happen? I could not reproduce shuch behaviour :( Are you pressing any keys at any point?

**Comment by KyoGrou** [comment]
No, I don't press any key. I guess this is another issue related to the tablet problem, even though I was using my mouse after I use the pen.
And I can't reproduce the problem when using Photopea at home so I guess I will try again tomorow.

**Comment by photopea** [comment]
I dont see any reason, why should a tablet and a mouse work differently in this case. 

I fixed the problem with Delete. Now, it deletes layers, when no paths or knots are selected.

**Comment by KyoGrou** [comment]
Well, there is that problem with the shift click using the tablet, so we can't really say they have some connection by magic or something.
I will try to reproduce the situation and watch the tool's behavior again tomorrow. Is there anything you can suggest to help you track the problem ?

**Comment by KyoGrou** [comment]
I can't reproduce the closing path problem today, guess there is no problem at all
