### ISSUE TITLE
Dragging layers between projects

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#234]
Many people are used to copying layers between projects by dragging them to the label of the new project at the top. It would be a nice feature to have.

**Comment by photopea** [comment]
Done.

**Comment by vfmatzkin** [comment]
I'm trying to do this (by dragging the layer or clicking 'Duplicate into..') but that makes the application freeze and the project where I want to paste the layer dissapears.

![Project in wich I want to paste the layer](https://user-images.githubusercontent.com/28831634/53245542-c03c2800-368c-11e9-945d-97c3d2e5e76b.png)

I can still see the first project but I can't do anything..

**Comment by photopea** [comment]
Hey! I tried to do this with some files and it worked well. Could you please send both of your files to support@photopea.com , so I could see what is going on?

**Comment by photopea** [comment]
Hi, the bug happened each time, when a layer with a Smart Filter was copied between different documents. I fixed it. Thank you! :)

**Comment by vfmatzkin** [comment]
Thank you a lot and congratulations for this amazing project!

Victor Franco Matzkin
