### ISSUE TITLE
Tools are not working

### ISSUE THREAD

**Issue by tarun66** [photopea/photopea#264]
Many of the tools like move tool resizing transformation tool colour picker and brush eraser , not working , it was worked for me before on the same device but not working now

**Comment by photopea** [comment]
Hi, do you mean on the touchscreen? You should be more specific. Everything wroks fine for me with a mouse.

**Comment by photopea** [comment]
There was a problem with a touchscreens, we just fixed it. But if your problem was something different, let us know.

**Comment by tarun66** [comment]
im using touch screen, but it worked for me when i used 3 days ago, now i
tried using 3 different devices but also same problem, tools like color
picker, eraser,brush, gradient , colour bucket,move etc.....are not working
. i tried using usb keyboard but also not all problems are fixed. thanks
for the response

**Comment by photopea** [comment]
We are updating Photopea every day, so problems can be introduced every day.

We fixed the issue with the touchscreen, so now, all tools should work on all touchscreens. Please, reload Photopea. Let me know if it works now.

**Comment by tarun66** [comment]
The problem is fixed now, tools r working fine, but there r still some
bugs, if we r working with two different images in two different tabs, the
history of transformation tool we used on first image is applying on second
image, even that window is closed also ,it's like conflicting two images

**Comment by photopea** [comment]
Hi, I don't understand what do you mean. When the image is closed, Photopea can not edit it.
Can you tell me some steps, how to reproduce your behavior?

**Comment by tarun66** [comment]
Please check this attachment, in this attachment u can see only one image
(window tab) is opened but the transformation tool is still appearing Which
I used to work with previous image in separate tab (not browser tab)

**Comment by photopea** [comment]
Hi, I can't see any attachment :(

**Comment by tarun66** [comment]
Now I'm sending u once again

**Comment by photopea** [comment]
Still cant see any attachment. Are you responding through emails? Please go to https://github.com/photopea/photopea/issues/264 and respond in a web interface.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
