### ISSUE TITLE
I still can't export

### ISSUE THREAD

**Issue by Stephperiodt** [photopea/photopea#3116]
someone answered saying i should just use incognito mode but it's still not working. everytime i export it turns into an .txt file

**Comment by photopea** [comment]
Can you record a video of how you export an image in Incognito window?

**Comment by Stephperiodt** [comment]
https://user-images.githubusercontent.com/82250255/114393772-c3346280-9bdd-11eb-9c25-5e45726a6a70.mp4

**Comment by photopea** [comment]
Turns out Chrome allows enabling extensions in Incognito mode.

Can you confirm, that either: you have no browser extensions, or, all of your extensions are disabled in Incognito mode?

https://lifehacker.com/enable-your-extensions-in-incognito-mode-for-safer-mor-1792622065

**Comment by Stephperiodt** [comment]
Yes they are disabled and the browser extentions i have do not affect photo pea (also i have used photopea in the past and this was not an issue)

**Comment by photopea** [comment]
Do you have an antivirus or any other program, that can rename downloaded files?

Can you paint something here: https://jspaint.app/ and save it to your computer?

**Comment by FlashofEarth01** [comment]
I am also having the exact same problem, even tried in Opera but the same problem occurs.

**Comment by photopea** [comment]
@FlashofEarth01 Have you disabled all browser extensions?

**Comment by FlashofEarth01** [comment]
I have disabled all my browser extensions, and I was able to export correctly. If you would like I would be willing to systematically switch them one one at a time to determine which one it might be so you can advise people in the future?

**Comment by Stephperiodt** [comment]
> Do you have an antivirus or any other program, that can rename downloaded files?
> 
> Can you paint something here: https://jspaint.app/ and save it to your computer?

Yes i am able to save there, i dont have an antivirus at the moment. i did have advast but i deleted that a while ago

**Comment by photopea** [comment]
Are you sure, that Photopea saves a PNG as TXT, but https://jspaint.app/  saves a PNG as a PNG? That is really strange.

**Comment by Stephperiodt** [comment]
Yes it does. It's really weird do you have any other ideas on what to do? x 
Sorry for the late reply

**Comment by photopea** [comment]
Photopea always asks a browser to save a file as a PNG. It is up to your device what exactly happens afterwards.

Can you truly disable all extensions? I mean for real, all extensions. Yes, all of them :) Not just those which you think could affect Photopea. And try it again?

**Comment by Stephperiodt** [comment]
I have disabled ALL of them. Nothing has changed.  I guess there isn't much else to do?

**Comment by photopea** [comment]
Do you have any antivirus or a firewall program, which chould modify files downloaded from the internet?

**Comment by Stephperiodt** [comment]
No, also i was able to export without any issues before this and i havent recently downloaded anything that would've made that happen

**Comment by photopea** [comment]
Could you record a video, where you show your chrome://extensions screen, and then, save a PNG in Photopea?

We had too many people lying to us, that they disabled their extensions, when actually they did not. Like here: https://github.com/photopea/photopea/issues/2294 . And I spent hours googling for another solutions, while the true solution was quite simple (but the person refused to disable extensions).

The problematic extensions is usually called "Download Manager".

**Comment by photopea** [comment]
Are there any news? I will close it for now.

**Comment by Stephperiodt** [comment]
i cant record but these are the extentions i have and i still have the issue. Also you seem angry, i apologize for asking
![image](https://user-images.githubusercontent.com/82250255/116690949-7d5d0400-a9fd-11eb-9d58-d490969efd83.png)

**Comment by photopea** [comment]
I am a bit angry, because I have been asking you to disable all extensions, and you still did not do it :(

Can you disable all extensions and check if files from Photopea are saved correctly? Use the switch at the bottom of extensions.

![image (1)](https://user-images.githubusercontent.com/15955558/116691739-8dec8a80-a9bb-11eb-9045-6610b7ef9c69.png)

**Comment by photopea** [comment]
Another solution for you would be to download and install another borwser.

A new browser does not have any extensions, so your extension, which renames files to TXT, would not run in that new browser.

**Comment by Stephperiodt** [comment]
I did tell you that i did disable them when i tested it, i just turned it back on after. I also used incognito mode like you told me and others to use and it didnt work so clearly its not the extentions.

**Comment by Stephperiodt** [comment]
Also yeah i think a new browser might help then x

**Comment by photopea** [comment]
Then, I really dont know what could be the problem :(

**Comment by SarahNoura** [comment]
@photopea Following on from this, last night it was all working fine when I went to bed, saving as PNG etc. But this morning, anything I open and edit is all saving as a .txt file even though I have selected to save as PNG, PSD, SVG, PDF etc. (I tried all formats to see if it made a difference). If I then proceed to open the saved .txt file and export it as PNG it will do this successfully. 

However, if I open a new blank project and copy the old project into the new project and export, it saves as a PNG quite happily. It only won't save an already existing project as a PNG. Nothing has changed between last night and this morning, the computer has been off. Also, when I go to the link provided to @Stephperiodt  https://jspaint.app/ it will also let me save from there as a PNG.

**Comment by photopea** [comment]
@SarahNoura I think it is caused by a browser extension. Try it in Incognito mode.

**Comment by SarahNoura** [comment]
@photopea I have tried it in incognito mode and on more than one browser with no success. Nothing has changed between last night and this morning (the computer was off) and last night it was fine, this morning it isn't. The only way I can get something to save as a PNG is to open the .txt file it originally saves it as and export it as PNG again.

**Comment by photopea** [comment]
Do you have any antiviruses installed?

**Comment by SarahNoura** [comment]
Nothing new and last night it wasn't a problem and it's not a problem this morning if I'm saving a new project

**Comment by photopea** [comment]
I would like to look at it myself. Would you let me look into your computer over TeamViewer? 

Please, write me a private message on Twitter https://twitter.com/photopeacom  or Facebook https://www.facebook.com/photopea/

**Comment by photopea** [comment]
There really was a bug in Photopea. If you opened a file, whose name started with a dot - `.` , like `.myfile.psd`, It was always exported as .TXT

I have fixed this bug. You can open files with any names now, and they should be saved under the right extension.

**Comment by photopea** [comment]
Many thanks to @SarahNoura for helping me discover this.

**Comment by photopea** [comment]
@Stephperiodt That was your case, too. Your file started with a dot, and your video shows a document name as ".psd". I could have noticed it from your video, but I did not :(

Anyway, now, even files starting with a dot should work fine.

**Comment by xFr0q** [comment]
> There really was a bug in Photopea. If you opened a file, whose name started with a dot `.` , like `.myfile.psd`, It was always exported as .TXT
> 
> I have fixed this bug. You can open files with any names now, and they should be saved under the right extension.

Its not fixed. I had a file start with . and it would export as a .txt and I stumbled across this forum. I used the method @SarahNoura used of opening the txt then exporting it.

**Comment by photopea** [comment]
@xFr0q Does it happen when you disable all your browser extensions? I think one of your browser extensions is breaking Photopea.
