### ISSUE TITLE
Preview blank when importing photo

### ISSUE THREAD

**Issue by nugget2021** [photopea/photopea#3209]
<img width="1440" alt="Screen Shot 2021-05-05 at 9 14 47 AM" src="https://user-images.githubusercontent.com/83709953/117146683-724dff00-ad82-11eb-9473-59561c7329d4.png">

**Comment by keul** [comment]
Same here. Tested on Firefox and Chrome

**Comment by photopea** [comment]
Guys, I am so sorry, it is fixed now.

**Comment by MrsMayo-NRHS** [comment]
I'm still having the issue

**Comment by keul** [comment]
Fixed for me, KUDOS for the fix speed!

**Comment by nugget2021** [comment]
Still having issue, it temporarily fixes the issue when CTRL/CMD+R is pressed.
