### ISSUE TITLE
Page no longer adapts to screen size

### ISSUE THREAD

**Issue by Daniel-Designer** [photopea/photopea#3658]
I am a longtime Photopea user and love photopea but,
for a few days when I open Photopea, the page no longer appears on my screen.
So that I always have to scroll down to create a folder with schortcuts, for example.

![grafik](https://user-images.githubusercontent.com/29311204/129486467-cf5e0847-714c-463c-b91b-9e7b1542bf47.png)
![grafik](https://user-images.githubusercontent.com/29311204/129486481-d7e57f5e-5c85-4083-91f4-8f390ad45430.png)

**Comment by photopea** [comment]
Is this Firefox? I could not reproduce such problem with Firefox. Is it Firefox Beta or something?

Can you use a stable firefox and disable all browser extensions? Does it help?

**Comment by Daniel-Designer** [comment]
Yes this is the Developer Edition of Firefox.
It is not a beta and after deactivating all browser extentions it still has the same error.
I really don't know what to do now.
A few days ago everything worked great.

**Comment by photopea** [comment]
I really think it is a bug in your web browser, and not in Photopea. You should report it to the creators of your web browser. Maybe you updated your browser in the meantime.

**Comment by photopea** [comment]
But in general, using a non-stable release of a browser usually means, that you are ready to accept minor problems at some websites.

**Comment by Daniel-Designer** [comment]
![grafik](https://user-images.githubusercontent.com/29311204/129623093-2617a26d-0f9c-4b0c-bafe-044b4c575437.png)
But for me with MS Edge it is still the same

**Comment by photopea** [comment]
That is weird, everything looks fine in my Edge. Is it Edge beta? Are you using Windows beta?

**Comment by Daniel-Designer** [comment]
Clean Edge installl.
No extentions.

No Windows beta that is the thinng.... it is wierd

**Comment by photopea** [comment]
So there really was a bug. It happened only when Photopea was in German (and some other languages, which have longer words than English). It should be fixed now.

I am sorry for not believing you earlier, thank you for your patience :)

**Comment by Daniel-Designer** [comment]
There is still a small scrollable area but that doesn't bother me anymore.

**Comment by photopea** [comment]
You are probably still seeing the old version. Reload it with Shift+F5.

**Comment by Daniel-Designer** [comment]
That doesn't fix it, but it doesn't really matter.
But thanks for creating this masterpeace.

**Comment by Daniel-Designer** [comment]
![grafik](https://user-images.githubusercontent.com/29311204/129628409-53841325-a431-48eb-bb46-27ce1f0e287d.png)
But now there is this wiered bug

**Comment by photopea** [comment]
Is it still Firefox Beta? have you tried it in a stable Firefox?

**Comment by agathaflc** [comment]
Hi, I'm having the same issue and here's how it happened:
1. Open Photopea in a maximized stable Chrome
2. Resize the Chrome window to half the screen
3. Maximize the Chrome window again
4. Photopea now has the empty space on the right

**Comment by photopea** [comment]
@agathaflc I am trying to do that, but Photopea always expands back to the full screen.

Can you show us a screenshot of what you see? Are you using any browser extensions?

**Comment by agathaflc** [comment]
Here you go:
![image](https://user-images.githubusercontent.com/15649769/142178046-8bc9739b-4d50-4c79-942d-3742c3c69bc0.png)

**Comment by photopea** [comment]
@agathaflc There should be advertisement on the right side.

Please, do not block ads in Photopea. Nobody wants to pay for Photopea Premium, so we would not exist if everybody hides ads like you do.
