### ISSUE TITLE
Bug Report: Shared PSD Links Not Opening

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5438]
I asked a person I was trying to help yesterday to share a link to their PSD project for me. Once they shared it, I was unable to open it. Photopea just got stuck at an "Opening" message. I figured they had done something wrong or copied something wrong and told them to try again.

Later that evening, I was helping another user on Reddit and shared one of my PSD project links with them. When they tried to open it this afternoon, it didn't work for them. And now, it doesn't work for me, either. Photopea just sits at an "Opening" message.

Would you please check to see if you notice anything out of the ordinary preventing these shared links from opening? Here is the link I shared that I can no longer open.
https://www.photopea.com/#iqt12HsY4.psd

**Comment by photopea** [comment]
I am very sorry. There was a condition, if nobody opens a link in the first hour after publishing, the file could be deleted. It did not mind before, because Photopea opened a link for you, automatically (so there was always at least one view).

I have fixed it, shared PSD files should exist at least for 6 months, even if nobody ever opens them during these 6 months.

**Comment by camoody1** [comment]
Thank you

**Comment by camoody1** [comment]
I just tried to help another person and their shared link still isn't opening. This is a link that was just created a few minutes ago.
https://www.photopea.com/#izEfzalVg.psd

**Comment by photopea** [comment]
So you created this link or someone else? I think that person could be using browser extensions, which are breaking the sharing functionality of Photopea. Also, some internet providers in Turkey block Backblaze (our cloud storage).

**Comment by camoody1** [comment]
Someone else here in the US created a link while I was working with them on Discord. They postes the link and I immediately tried it. It just sits on Loading.🤷🏽‍♂️

**Comment by photopea** [comment]
Can you replicate it? I need some way to replicate it.

Also, are you 100% sure that person was not using any browser extensions?

**Comment by camoody1** [comment]
I have no idea if he had extensions. He was just some random young guy who needed some help on a project. I just created my own share and it immediately worked. I'll create another one and let it sit for awhile before opening it to see if it works later.

**Comment by camoody1** [comment]
I opened my own shared link 6 hours after creating it and it worked fine. The only thing left to test if there's a problem with opening someone ELSE'S link for some reason. To test that possibility, I am posting a shared link here for you to open. Let me know if it opens for you. If it works, consider this issue closed, again.
www.photopea.com/#inWe7mEus.psd

**Comment by photopea** [comment]
I can open your link. 

I think you are wasting time. If a link works for a person with a proper internet, it works for everyone with a proper internet. If a link does not work for a person with a proper internet, a link works for nobody with a proper internet.

It seems like you have a proper internet, and your firend does not (caused by browser extensions or an internet provider).
