### ISSUE TITLE
Unable to Create Any Project With Photopea

### ISSUE THREAD

**Issue by coderanusha13** [photopea/photopea#5525]
I am trying to create a new project and also any existing psd, but I am not being able to do it. No pop up of new window is opening and I am not being able to create any new project.

**Comment by CrafterYT123** [comment]
Same, I cant do a project i need to do today which is making roblox GFX and i cant load my template i use.

**Comment by ZachNAus** [comment]
Same, Cannot open a project in browser or in the installed version. I've tried New project and going with a blank, a template, dragging images in, directly giving access to files. Nothing.

**Comment by haakonnessjoen** [comment]
Yeah, I am unable to open files both with the "open from computer" dialog, and the "Local computer" browser.

**Comment by cbayiha** [comment]
Same here.

**Comment by AirGEL** [comment]
having the same problem as well

**Comment by BusyBeeFabric** [comment]
same issue here too - very frustrating as I had time put aside today to do some projects :(

**Comment by dxmi13** [comment]
Same.

**Comment by tntsoft** [comment]
![image](https://user-images.githubusercontent.com/5844176/231429405-46cce55b-4d0d-4795-bab5-ff6e53effe4d.png)
![image](https://user-images.githubusercontent.com/5844176/231429467-70d45259-770f-4aea-8cf6-8183c55c8e92.png)

This is the issue. Please take a peak and deploy a fix, seems to be something to do with inexistant ```config.tags```.

**Comment by pando-thibaut** [comment]
Same here

**Comment by NemesisBP** [comment]
Same problem for me too.
Nothing works

**Comment by Ali-5151** [comment]
Probably the server is overloaded, down or unreachable because of a network problem, outage or a website maintenance is in progress...

**Comment by coderanusha13** [comment]
Right. Photopea Team please look urgently to this matter. :P

**Comment by JorayLing** [comment]
Same here.

**Comment by JorayLing** [comment]
thank u,photopea is really great,I wish you can do better and better




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "photopea/photopea"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月12日(星期三) 晚上6:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [photopea/photopea] Unable to Create Any Project With Photopea (Issue #5525)





 
Right. Photopea Team please look urgently to this matter. :P

**Comment by sudtichai** [comment]
Same here

**Comment by NemesisBP** [comment]
> working well in incognito mode ( Private Window )

I tried in incognito, but it doesn't work.
Tried different browsers too, incognito/private window, clear cookies/cache .....

**Comment by nocdebalo** [comment]
maybe they will fix this issue soon

**Comment by camoody1** [comment]
> maybe they will fix this issue soon

In Cognito working for me, too. And I'm on a mobile phone with no browser extensions.

**Comment by sudtichai** [comment]
use on microsoft edge

**Comment by NemesisBP** [comment]
> > maybe they will fix this issue soon
> 
> In Cognito working for me, too. And I'm on a mobile phone with no browser extensions.

Is working in incognito because it seems that the issue has been fixed.
I just did clear history in the browser for the last hour and works.

**Comment by camoody1** [comment]
Clear your cache and try it again. It's now working for me after clearing cache.

**Comment by NemesisBP** [comment]
> use on microsoft edge

is not browser related, it did not work on any of them, Edge, Firefox, Chrome .... etc.
now is working

**Comment by camoody1** [comment]
I contacted the developer directly and he says that it is now fixed. He did say that you may need to clear your cache. My mobile device is working correctly after clearing the browser cache.

**Comment by photopea** [comment]
Sorry guys, it is fixed now, just clear your cache or wait 30 minutes.

**Comment by NemesisBP** [comment]
> Sorry guys, it is fixed now, just clear your cache or wait 30 minutes.

thank you very much for the fast fix
I can conform that by clearing cache is working.

**Comment by xilehence** [comment]
I am also having trouble running Photopea with Firefox (v. 109.0.1), even though it works fine in Safari (on MacOS Monterey 12.6.3). However, it seems to work fine in a Private Window in Firefox ("Incognito" in Chrome). However, disabling the Extensions (Add-Ons) via Menu > Add-Ons and Themes > Extensions and Themes, as had been recommended by https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/, didn't fix the problem and allow opening non-private windows. I tried clearing the Photopea cache via Menu > Settings > Privacy & Security > Cookies and Site Data > Manage Data, selecting and clearing only the Photopea.com, but that didn't work either. So only work-around i know now is Private Window in Firefox or possibly just using another browser (although i haven't checked Edge, Chrome, Opera, Vivaldi, etc.).

**Comment by photopea** [comment]
Could you tell us what problem do you have with running Photopea in Firefox? We have thousands of users who use firefox, seems like it works for them just fine. I also never had any problems with Photopea in Firefox.

**Comment by xilehence** [comment]
Thanks for checking, Ivan.

I have spent some time investigating this, clearing caches, launching troubleshooting mode, etc.,
and still don’t understand the situation.
My computer (Mac) @ home can’t run Photopea in Firefox without using a Private Window,
but my computer @ school (also a Mac) can.
Launching in safe mode (disabling extensions and add-ons) doesn’t help.
(Latest version of Firefox for both, but older computer at home is running macOS Big Sur, while newer computer at school is running macOS 13 Ventura,
but i don’t know if that is significant.)

I don’t know what the difference is, but for now you can close the ticket or whatever it is.
If i find out what the problem is i will let you know.

Thanks again for a great product.
My students especially enjoyed recently implemented deepfake capability.
Btw, i read that you are making some good money from Photopea, and it is well deserved!

Prof. Michael Cohen <https://u-aizu.ac.jp/~mcohen>, Ph.D.
Spatial Media Group <https://u-aizu.ac.jp/~mcohen/spatial-media/>
(90 Kamiiawase) Tsuruga, Ikki-machi
University of Aizu <https://u-aizu.ac.jp/en/>
Aizu-Wakamatsu, Fukushima  965-8580
Japan

voice: [+81](242)37-2537
fax: [+81](242)37-2772
e·mail: ***@***.*** ***@***.***>

**Comment by photopea** [comment]
I just installed Firefox 112.0.2 onto my macbook with Mac OS Big Sur. Photopea seems to work fine. You never told us what exactly happens in your case (you see a fully black webpage, you see something else ... ?)

Did you try to remove Firefox from your computer and install it again? Many browsers encourage you to enable crazy options when installing. Regular users are ready to agree with anything, as long as it is called "security improvement", "privacy enhancement" etc.
