### ISSUE TITLE
New question about correctly work executeAction-based scripts

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5597]
Good evening!
Dear Photopea, for reasons well known to you, user scripts in Photoshop (and Fotopea, of course) are largely based on executeAction
For my amators scripts project today I checked this commands sets in PS and in Photopea
1. Filters without parametrs: [https://photopeaactionslib.olegpustovoit.repl.co/Experiments.jsx](url)
2. Filters with integer parametrs: [https://photopeaactionslib.olegpustovoit.repl.co/Experiment2.jsx](url)
3. Filters with UnitDouble parametrs: [https://photopeaactionslib.olegpustovoit.repl.co/Experiment3.jsx](url)
All this jsx work in PS (yes, becouse this parts ScriptingListenerJS.log) and no work in Photopea
First group from Experiments.jsx stopped on "undefined" parametr in executeAction()...

But problem of this incompatibility seems to have common roots. But I really want the beloved Photopea not to be inferior to Photoshop in the automation of work with processes.

Thank you for your work and prompt attention to our modest local tasks that we want to solve with the help of Fotopea!

**Comment by photopea** [comment]
I think I have fixed it. Could you try it?

BTW. this script already worked in Photopea, so it is not clear to me why did you write it down:

    var idBlrM = charIDToTypeID( "BlrM" );
    executeAction( idBlrM, undefined, DialogModes.NO );

Please, show me only scripts which do not work in Photopea.

**Comment by Pt-home** [comment]
Ok, great thanks, I'll try to test them soon and let you know the result. I'm sorry, probably, with BlurM I was not quite attentive...

By the way, about Problem 2 from closed issue [https://github.com/photopea/photopea/issues/5596](url)
Script with Spt still doesn't want to work in Photopea: [https://photopeaactionslib.olegpustovoit.repl.co/scriptSpt.jsx](url)
Everything is waiting for the parameter FlRs.v

**Comment by Pt-home** [comment]
I checked the scripts of the current issue.
Three functions are NOT WORKING yet:
Mosaic: [https://photopeaactionslib.olegpustovoit.repl.co/scriptMsc.jsx](url)
Median: [https://photopeaactionslib.olegpustovoit.repl.co/scriptMdn.jsx](url)
Blur: [https://photopeaactionslib.olegpustovoit.repl.co/scriptBlr.jsx](url)
The rest are all OK now...

**Comment by photopea** [comment]
Ok, so the bug was with filters whch had "three letters and a space", it is fixed now :)
