### ISSUE TITLE
Loading pop up keep on appears on chrome

### ISSUE THREAD

**Issue by solid18194** [photopea/photopea#7830]
Loading screen keep on appears on chrome browser

**Comment by photopea** [comment]
Try uninstall some plugins or other stuff, press Window - Plugins, Installed (on the left side), uninstall some items.

**Comment by Miley-pp** [comment]
Hello, I have the same issue where the **loading screen** doesn't go away after installing plugins...

![Image](https://github.com/user-attachments/assets/6ccb7cc3-3572-48c2-bc60-5115f4719ab5)

--- I tried uninstalling all plugins but error persist, even uninstalled PP and tried using web version same issue

Please help...

**Comment by photopea** [comment]
Look into Edit - Local Storage, and delete the items there. Maybe there are items (like fonts) which Photopea can not process properly. You could send us these items, if you think Photopea should be able to process them.

**Comment by Miley-pp** [comment]
I looked into your recommendations and attached the screen snip. there were/are no files to delete or clear. 

issue unchanged

![Image](https://github.com/user-attachments/assets/499a6fdc-1cfa-4b26-aef3-7fc5c4440b80)

**Comment by photopea** [comment]
Okay, and could you show us your installed plugins? Press Window - Plugins - Installed.

Otherwise, clear your website data, and it should fix it: https://www.photopea.com/tuts/photopea-opens-up-old-files/#:~:text=Clearing%20Website%20Data

**Comment by Miley-pp** [comment]
Thank you for taking the timeout to attend my issue.
i tried both recommendations

- attached is snip screen of my plug-ins (also note, although it says installed , its actually not there)
- clearing the website does fix load screen banner issue, but i still cannot install any plug-ins

![Image](https://github.com/user-attachments/assets/3e1404c0-fdac-4484-81fa-341cfdc20259)

**Comment by photopea** [comment]
Could you uninstall that plugin? press the "Uninstall" and reload Photopea.

**Comment by Miley-pp** [comment]
Sure, ill do that now brb

**Comment by Miley-pp** [comment]
The 1st attached is me installing the plug-in
the 2nd attachment is me showing the results and load screen issue

![Image](https://github.com/user-attachments/assets/a0b3ee57-c237-48eb-b64d-75a7bbd69168)

![Image](https://github.com/user-attachments/assets/c86bcb13-7737-46f4-9b37-c43c528d571b)

**Comment by photopea** [comment]
I asked you to uninstall this plugin and use Photopea with no plugins. Could you try that?

**Comment by Miley-pp** [comment]
This is Photopea without plug-ins.

the issue arises when trying to use plug-ins

![Image](https://github.com/user-attachments/assets/eadc077f-9f5e-41df-9831-392e6e798d80)

**Comment by photopea** [comment]
Where do you live? Do you live in Turkey?

**Comment by Miley-pp** [comment]
No, South Africa

**Comment by photopea** [comment]
Can you load this link and save it to your computer? https://f000.backblazeb2.com/file/pp-resources/7ndDJ2gL

Can you open our PSD templates? Like this one? https://www.photopea.com/#t3ZbOmi07

**Comment by Miley-pp** [comment]
Hello.

no to both options. I can however open my own PSD files saved from previous projects

see error attached when click 1st link

![Image](https://github.com/user-attachments/assets/e5506e52-c351-49de-8f93-624b73a09cb6)

**Comment by Miley-pp** [comment]
in fact tried other stock templates on photopea, i cannot open any of the ones i tried clicking on

**Comment by photopea** [comment]
I think your internet provider is blocking Backblaze, which is our cloud storage provider.

To use plugins of Photopea, you must be able to open e.g. this address: https://f000.backblazeb2.com/file/pp-resources/7ndDJ2gL . Otherwise, Photopea will start loading the plugin, but the "Loading" message will never go away.

Ask your internet provider why do they block websites.

**Comment by Miley-pp** [comment]
Ill check with them thank you for trying to help

**Comment by joelasan** [comment]
this was working for me last few weeks and it stopped 2 days ago.. same network, same laptop

**Comment by photopea** [comment]
@joelasan what stopped working?

**Comment by JoelAsante** [comment]
I see loading, but nothing loads. no psd files can load/upload

**Comment by photopea** [comment]
Try to uninstall installed plugins, press Window - Plugins, Installed (on the left), uninstall everything.

**Comment by JoelAsante** [comment]
I dont have any plugins

![Image](https://github.com/user-attachments/assets/95448644-13d1-4df4-9f45-4f9fb07e3df1)

**Comment by photopea** [comment]
Then, look into Edit - Local Storage, try to delte some or all files there.

**Comment by JoelAsante** [comment]
NOPE There's nothing there
![Image](https://github.com/user-attachments/assets/5b6766c6-d94e-423e-8145-6bba1e70351a)

**Comment by photopea** [comment]
Could you try to use Photopea in the Incognito mode, as described here? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by JoelAsante** [comment]
Same thing in incognito mode

![Image](https://github.com/user-attachments/assets/13541bb5-83a2-487e-8831-3df7019842c8)

**Comment by photopea** [comment]
What web browser do you use? Could you share a screenshot of your whole screen, without cutting away a browser UI?

**Comment by JoelAsante** [comment]
I stopped using it because it just didn't work

**Comment by photopea** [comment]
Photopea always works well in a browser with no browser extensions. So I am pretty sure that you installed extensions to your browser, and you allowed them to have a full access to Photopea. Or you use the Brave browser, which always breaks Photopea.

**Comment by photopea** [comment]
I will close it now. If you still have any problems, please, make a new report.
